### ISSUE TITLE
Please correct npm maintainers configuration.

### ISSUE THREAD

**Issue by GermanBluefox** [AlCalzone/ioBroker.sensebox#71]
## ioBroker adapter checker for npm access

Access right check for adapter sensebox returned the following issue:

Bluefox was not found in the collaborators on NPM!.
Please execute in adapter directory: "npm owner add bluefox iobroker.sensebox"

Current maintainers are 
    alcalzone <d.griesel@gmx.net>

Please fix the above error as soon as possible.
All adapters listed at ioBroker repositories must have 'bluefox' added as maintainer.

Future version updates at the repositories will be suspended until this problem is fixed.

**Comment by mcm1957** [comment]
@AlCalzone 
Please add bkuefox whenever you have time to get the list a lttle bit shorter.
Thanks

**Comment by AlCalzone** [comment]
done
